name: nian_dev_kit
description: "念安科技-开发工具"
version: 0.0.1
homepage: "https://github.com/Aquarius-M/nian_dev_kit"
repository: "https://github.com/Aquarius-M/nian_dev_kit"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  get_server: ^1.2.1
  
  tuple: ^2.0.2
  # base_utils:
  #   path: ../base_utils
    # git:
    #   url: https://github.com/Aquarius-M/base_utils.git
  shared_preferences: ^2.2.2
  image: ^4.1.7
  touch_indicator: ^2.0.0
  platform: ^3.1.4
  system_info2: ^4.0.0
  device_info_plus: ^10.1.0
  string_scanner: ^1.2.0
  sqlite_viewer: ^1.0.5
  fluttertoast: ^8.2.4
  path: ^1.9.0
  path_provider: ^2.1.2
  logger: ^2.2.0

  network_info_plus: ^5.0.3
  package_info_plus: ^8.0.0

  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.nian.plugin.nian_dev_kit
        pluginClass: NianDevKitPlugin
      ios:
        pluginClass: NianDevKitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
